name: Timetable Check
on: push
jobs:
  run_timetable_check:
    name: Run Timetable Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python for Parsing Output
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install RailOSTools
        run: python -m pip install "git+https://github.com/Railway-Op-Sim/railostools.git@v0.6.1#egg=railostools&subdirectory=python"

      - name: Validate Timetable
        run: |
          set -e
          for ttb in $(find -name "*.ttb"); do
            echo "Validating $ttb"
            railostools validate $ttb || (echo "Validation failed." && exit 1)
            echo "Validation succeeded."
          done
